name: build-dev
on:
  push:
    branches:
      - main
jobs:
  build-dev:
  name: buildDev
  runs-on: ubuntu-latest
  steps:

      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12.18.3'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build-dev
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: '~/public'
